### ISSUE TITLE
setup in test_users sending wrong password after password reset

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec-tests-2#1]
In `test_user.py`, before each test, `setUp()` is called and the passenger logs in using `PASSENGER_EMAIL` and `PASSENGER_PASSWORD`. However, in `test_03_change_password`, the password for is changed to `NekaSifra456` and after that `PASSENGER_PASSWORD` is no longer valid, so all further tests fail because login fails.
The test could pass if `newPassword` in test03 is set to be equal to `oldPassword`.

@greenenvy

**Comment by asistenti** [comment]
Dodacu jedan ,,test,, na kraju koji vraca sifru u inicijalno stanje.

**Comment by asistenti** [comment]
Zapravo sam skontao da su mi pogresne vrednosti u user_data.py, tj. pogresno je napisano, umesto ,,NekaSifra123,, je napisano ,,NekaSfira123,,. To sam prepravio, a dodao u user_data test_53 koji bi trebao da resi vracanje sifre.

**Comment by magley** [comment]
Problem i dalje postoji jer se testovi izvršavaju sekvencijalno, po nazivu. Svi testovi posle `03` će pasti jer `setUp` i dalje pokušava da se uloguje sa starom šifrom. Šifra treba ili da se vrati odmah posle trećeg testa (u samom testu, pošto odvojen test slučaj koji revertuje šifru neće moći da se pokrene iz istog razloga) ili da test `03` ima isti old password i new password.

**Comment by asistenti** [comment]
Da u pravu si, nisam lepo protumacio sta si napisao. Msm da je sad reseno. Hvala.
