### ISSUE TITLE
[ride] Delete favorites wrong credentials

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec-tests-2#10]
`test_51_delete_favorites_forbidden` implies that admins cannot delete favorite rides.
`test_52_delete_favorites_not_exist` expects a 404, but since it's called with admin credentials, it should return 403.
`test_53_delete_favorites` expects a 204, but since it's called with admin credentials it should return 403.

Should the last two tests have `jwt=self.passenger` instead of `jwt=self.admin`?

**Comment by asistenti** [comment]
Fixed
