### ISSUE TITLE
[driver] Work hour inconsistency

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec-tests-2#6]
When a driver logs in, he automatically "clocks in" and his work hour beings. Calling a `POST work-hours` after that will fail because he already has an ongoing shift.

One of the driver's tests overlooks this scenario: `test_52_add_working_hour`, written as a happy flow test, should actually fail. 

Unfortunately, all the subsequent tests for working hours depend on this test succeeding, because `self.__class__.driver_working_hour_id` and `self.__class__.driver_working_hour` are defined in that test.

**Comment by lazer-nikolic** [comment]
Nothing about automatic clock-in is mentioned in the specification. It is fine, however, if you implemented it in your project like that. Just make sure to remind us why the test is failing.
