### ISSUE TITLE
[ride] Wrong passenger count assertion

### ISSUE THREAD

**Issue by magley** [asistenti/iss-swagger-spec-tests-2#7]
in `test_05_create_ride`, the assertion `self.assertEqual(len(response_body['passengers']), 2)` fails because only 1 passenger is added.
The same issue occurs in several other tests in that file.

**Comment by asistenti** [comment]
Ovo zavisi kako se protumaci. Posto i admin potencijalno moze da otvara detalje neke voznje, mozda ce neko implementirati da se u listi passenger-a nalazi i onaj koji je porucio voznju i onaj koji je uvezan. Ovo prepravite lokalno u vasem testu pa naglasite meni/Lazaru.
